# Generated by Django 3.2.11 on 2022-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=50)),
                ('start_time', models.DateField()),
                ('deadline', models.DateField()),
                ('type_of_event', models.CharField(choices=[('Sportowe', 'Sportowe'), ('Kulturowe', 'Kulturowe'), ('Rozrywkowe', 'Rozrywkowe')], max_length=30)),
            ],
        ),
    ]
