# Generated by Django 3.2.11 on 2022-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0002_auto_20220409_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='x_miejsca',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='y_miejsca',
            field=models.FloatField(null=True),
        ),
    ]
