# Generated by Django 3.1.5 on 2022-04-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0003_auto_20220410_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
