# Generated by Django 3.1.5 on 2022-04-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0005_auto_20220411_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link_do_miejsca_wydarzenia',
            field=models.URLField(blank=True, null=True),
        ),
    ]
