# Generated by Django 3.2.11 on 2022-05-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0010_auto_20220514_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='zdjecia',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='eventy', to='main_backend.event'),
        ),
    ]
