# Generated by Django 3.2.11 on 2022-05-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_backend', '0011_zdjecia_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_backend.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Zdjecia',
        ),
    ]
